---
kind: pipeline
type: exec
name: deploy_staging

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker build . --tag noagreements:latest
  - name: stop_and_remove
    commands:
      - docker rm --force noagreements-site
  - name: run
    environment:
      POSTGRES_PASSWORD:
        from_secret: pg_password
      SECRET_KEY:
        from_secret: secret_key
      HOST: noagreements.abeforweb.me
      EMAIL_HOST: mail.noagreements.co
      EMAIL_PORT: 465
      EMAIL_HOST_USER: noreply@noagreements.co
      EMAIL_HOST_PASSWORD:
        from_secret: email_password
    commands:
      - >-
        docker run -p 8000:8000
        --network noagreements-net
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        -e SECRET_KEY=$SECRET_KEY
        -e HOST=$HOST
        -e EMAIL_HOST=$EMAIL_HOST
        -e EMAIL_PORT=$EMAIL_PORT
        -e EMAIL_HOST_USER=$EMAIL_HOST_USER
        -e EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        --name noagreements-site
        -v noagreements-static:/code/static
        -d noagreements:latest
  - name: migrations
    commands:
      - docker exec noagreements-site bash -c 'python manage.py migrate'
trigger:
  branch:
    - development

---
kind: pipeline
type: ssh
name: deploy_prod

server:
  host:
    from_secret: prod_host
  user:
    from_secret: prod_user
  ssh_key:
    from_secret: ssh_key
steps:
  - name: build
    commands:
      - docker build . --tag noagreements:latest
  - name: stop_and_remove
    commands:
      - docker rm --force noagreements-site
  - name: run
    environment:
      POSTGRES_PASSWORD:
        from_secret: pg_password
      SECRET_KEY:
        from_secret: prod_secret_key
      HOST: 162.243.168.205
      EMAIL_HOST: mail.noagreements.co
      EMAIL_PORT: 465
      EMAIL_HOST_USER: noreply@noagreements.co
      EMAIL_HOST_PASSWORD:
        from_secret: email_password
    commands:
      - >-
        docker run -p 8000:8000
        --network noagreements-net
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        -e SECRET_KEY=$SECRET_KEY
        -e HOST=$HOST
        -e EMAIL_HOST=$EMAIL_HOST
        -e EMAIL_PORT=$EMAIL_PORT
        -e EMAIL_HOST_USER=$EMAIL_HOST_USER
        -e EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        --name noagreements-site
        -v noagreements-static:/code/static
        -d noagreements:latest
  - name: migrations
    commands:
      - docker exec noagreements-site bash -c 'python manage.py migrate'
trigger:
  branch:
    - master
  event:
    exclude:
      - cron
---
kind: pipeline
type: ssh
name: backup_prod

server:
  host:
    from_secret: prod_host
  user:
    from_secret: prod_user
  ssh_key:
    from_secret: ssh_key
steps:
  - name: recreate pgpass
    environment:
      PGPASSWORD:
        from_secret: pg_password
    commands:
      - rm -f ~/.pgpass
      - echo "0.0.0.0:5432:noagreements:noagreements:$PGPASSWORD" > /root/.pgpass
      - chmod 0600 /root/.pgpass
  - name: make_backup
    commands:
      - pg_dump -w -F d -f /root/daily_backup -U noagreements noagreements
trigger:
  event:
    - cron

---
kind: pipeline
type: exec
name: import_backup

platform:
  os: linux
  arch: amd64

steps:
  - name: recreate pgpass
    environment:
      PGPASSWORD:
        from_secret: pg_password
      PROD_HOST:
        from_secret: prod_host
    commands:
      - rm -f ~/.pgpass
      - echo "localhost:5432:noagreements:noagreements:$PGPASSWORD" > /root/.pgpass
      - echo "$PROD_HOST:5432:noagreements:noagreements:$PGPASSWORD" >> /root/.pgpass
      - chmod 0600 /root/.pgpass
  - name: remove old old backup
    commands:
      - rm -rf /root/daily_backup_old
  - name: move old backup
    commands:
      - "[ ! -d /root/daily_backup ] || mv /root/daily_backup /root/daily_backup_old"
  - name: get backup
    environment:
      PROD_HOST:
        from_secret: prod_host
    commands:
      - pg_dump -w -F d -f /root/daily_backup -U noagreements -h $PROD_HOST noagreements
  - name: remove db
    commands:
      - dropdb --if-exists -U postgres noagreements
  - name: import backup
    commands:
      - pg_restore -C -U postgres -d postgres /root/daily_backup
trigger:
  event:
    - cron
