---
kind: pipeline
type: exec
name: deploy_staging

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker build . --tag noagreements:latest
  - name: stop_and_remove
    commands:
      - docker rm --force noagreements-site
  - name: run
    environment:
      POSTGRES_PASSWORD:
        from_secret: pg_password
      SECRET_KEY:
        from_secret: secret_key
      HOST: noagreements.abeforweb.me
      EMAIL_HOST: mail.noagreements.co
      EMAIL_PORT: 465
      EMAIL_HOST_USER: noreply@noagreements.co
      EMAIL_HOST_PASSWORD:
        from_secret: email_password
    commands:
      - >-
        docker run -p 8000:8000
        --network noagreements-net
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        -e SECRET_KEY=$SECRET_KEY
        -e HOST=$HOST
        -e EMAIL_HOST=$EMAIL_HOST
        -e EMAIL_PORT=$EMAIL_PORT
        -e EMAIL_HOST_USER=$EMAIL_HOST_USER
        -e EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        --name noagreements-site
        -v noagreements-static:/code/static
        -d noagreements:latest
  - name: migrations
    commands:
      - docker exec noagreements-site bash -c 'python manage.py migrate'
trigger:
  branch:
    - development

---
kind: pipeline
type: ssh
name: deploy_prod

server:
  host:
    from_secret: prod_host
  user:
    from_secret: prod_user
  ssh_key:
    from_secret: ssh_key
steps:
  - name: build
    commands:
      - docker build . --tag noagreements:latest
  - name: stop_and_remove
    commands:
      - docker rm --force noagreements-site
  - name: run
    environment:
      POSTGRES_PASSWORD:
        from_secret: pg_password
      SECRET_KEY:
        from_secret: prod_secret_key
      HOST: 162.243.168.205
      EMAIL_HOST: mail.noagreements.co
      EMAIL_PORT: 465
      EMAIL_HOST_USER: noreply@noagreements.co
      EMAIL_HOST_PASSWORD:
        from_secret: email_password
    commands:
      - >-
        docker run -p 8000:8000
        --network noagreements-net
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        -e SECRET_KEY=$SECRET_KEY
        -e HOST=$HOST
        -e EMAIL_HOST=$EMAIL_HOST
        -e EMAIL_PORT=$EMAIL_PORT
        -e EMAIL_HOST_USER=$EMAIL_HOST_USER
        -e EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        --name noagreements-site
        -v noagreements-static:/code/static
        -d noagreements:latest
  - name: migrations
    commands:
      - docker exec noagreements-site bash -c 'python manage.py migrate'
trigger:
  branch:
    - master
---
kind: pipeline
type: ssh
name: backup_prod

server:
  host:
    from_secret: prod_host
  user:
    from_secret: prod_user
  ssh_key:
    from_secret: ssh_key
steps:
  - name: make_backup
    environment:
      PGPASSWORD:
        from_secret: pg_password
    commands:
      - pg_dump -F d -f /root/daily_backup -U noagreements noagreements
trigger:
  event:
    - cron

---
kind: pipeline
type: exec
name: import_backup

platform:
  os: linux
  arch: amd64

steps:
  - name: remove old backup
    commands:
      - rm -rf /root/daily_backup
  - name: get backup
    environment:
      PGPASSWORD:
        from_secret: pg_password
      PROD_HOST:
        from_secret: prod_host
    commands:
      - pg_dump -F d -f /root/daily_backup -U noagreements -h $PROD_HOST noagreements
  - name: import backup
    environment:
      PGPASSWORD:
        from_secret: pg_password
    commands:
      - pg_restore -c -U noagreements -d noagreements /root/daily_backup
trigger:
  event:
    - cron
