version: '3'

services:
  db:
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  web:
    volumes:
      - .:/code
    command: ./docker-entrypoint.sh rundev
    environment:
      - ENV=devdocker
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
