version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    depends_on:
      - db

  smtp:
    image: namshi/smtp
    environment:
      - "MAILNAME=noagreements.co"
    ports:
    - 25:25
