version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    depends_on:
      - db

  smtp:
    image: "docker.pkg.github.com/namshi/docker-smtp/smtp:0.0.2"
    environment:
      - "MAILNAME=noagreements.co"
    ports:
    - 25:25