# Generated by Django 3.1.1 on 2020-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='tag',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
