# Generated by Django 3.2 on 2021-04-18 22:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210414_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
